#/bin/bash

#PBS -N mnist_Cheng_xgb
#PBS -l select=1:ncpus=16:mem=20gb:ngpus=1:gpu_model=p100
#PBS -l walltime=72:00:00

module purge
module load anaconda3/5.0.1 gurobi/7.0.2 
source activate robusttrees_py37
cd ~/8100/8100-Intro-to-AI-project/report3_codes/Cattack_codes
python cheng_attack_driver.py mnist ../../data/ori_mnist.test0 ../../report3_models/xgb/ori_mnist_unrobust_new/0200.model 10 784