#/bin/bash

#PBS -N breast_cancer_Kan_rxgb
#PBS -l select=1:ncpus=16:mem=20gb:ngpus=1:gpu_model=k40
#PBS -l walltime=72:00:00

module purge
module load anaconda3/5.0.1 gurobi/7.0.2 
source activate robusttrees_py37
cd ~/8100/8100-Intro-to-AI-project/report3_codes/Kattack_codes
python xgbKantchelianAttack.py -dn=breast_cancer -mn=rxgb -d=../../data/breast_cancer_scale0.test -m=../../report3_models/rxgb/breast_cancer_robust/0004.model -c=2